// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feedbyurl.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const feedByUrl = `-- name: FeedByUrl :one
SELECT id,name FROM feeds 
WHERE url = $1
`

type FeedByUrlRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) FeedByUrl(ctx context.Context, url string) (FeedByUrlRow, error) {
	row := q.db.QueryRowContext(ctx, feedByUrl, url)
	var i FeedByUrlRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
