// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getfeedfollowersforuser.sql

package database

import (
	"context"
)

const feedFollowersForUser = `-- name: FeedFollowersForUser :many
Select users.name as user_name, feeds.name as feed_name from feed_follows
INNER JOIN users on user_id = users.id
INNER JOIN feeds on feed_id = feeds.id
WHERE users.name = $1
`

type FeedFollowersForUserRow struct {
	UserName string
	FeedName string
}

func (q *Queries) FeedFollowersForUser(ctx context.Context, name string) ([]FeedFollowersForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, feedFollowersForUser, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedFollowersForUserRow
	for rows.Next() {
		var i FeedFollowersForUserRow
		if err := rows.Scan(&i.UserName, &i.FeedName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
