// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: markfeed.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const markFeed = `-- name: MarkFeed :exec
UPDATE feeds
SET last_fetched_at = $2, updated_at = $2
WHERE id = $1
`

type MarkFeedParams struct {
	ID            uuid.UUID
	LastFetchedAt sql.NullTime
}

func (q *Queries) MarkFeed(ctx context.Context, arg MarkFeedParams) error {
	_, err := q.db.ExecContext(ctx, markFeed, arg.ID, arg.LastFetchedAt)
	return err
}
